import { type WebhookEnvelope, isRecord } from '../shapes/common.js'

import payloads from './payloads.json' with { type: 'json' }

/**
 * The event types the v1 integration subscribes to.
 *
 * `list.subscribed` fires only on a first INSERT with status active, so
 * "New List Subscriber" needs `list.confirmed` and `list.resubscribed` as well or
 * it silently misses every returning contact.
 */
export const V1_EVENT_TYPES = [
  'contact.created',
  'contact.updated',
  'list.subscribed',
  'list.confirmed',
  'list.resubscribed',
  'list.unsubscribed',
  'segment.joined',
  'segment.left',
] as const

export type NotifuseEventType = (typeof V1_EVENT_TYPES)[number]

/**
 * Returns the recorded delivery envelope for one event type.
 *
 * `payloads.json` is generated by a backend integration test that inserts a real
 * record and captures the resulting `webhook_deliveries.payload`, so it is the
 * only trustworthy description of what a subscriber receives: the payloads are
 * assembled by PL/pgSQL trigger bodies that no compiler in this repository reads.
 * Build every `sample` and every fixture from this, never by hand — and when a
 * payload is missing, fix the generator rather than writing one here.
 *
 * The envelope is rebuilt rather than handed out, so a caller cannot mutate the
 * loaded module and change what the next caller sees.
 */
export const sampleEnvelope = (eventType: NotifuseEventType): WebhookEnvelope => {
  const envelope = payloads.events[eventType]
  if (!isRecord(envelope)) {
    throw new Error(`no recorded payload for ${eventType}; regenerate payloads.json`)
  }

  return {
    id: String(envelope.id),
    type: String(envelope.type),
    workspace_id: String(envelope.workspace_id),
    timestamp: String(envelope.timestamp),
    data: isRecord(envelope.data) ? { ...envelope.data } : {},
  }
}
